eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: student-service
          uri: lb://students-service
          predicates:
            - Path=/api/v1/students/**
        - id: school-service
          uri: lb://schools-service
          predicates:
            - Path=/api/v1/schools/**